#!/bin/bash
#aws lambda update-function-code --function-name arn:aws:lambda:us-east-1:172849472790:function:tweeter_login --zip-file fileb:///Users/taylor_west/Library/CloudStorage/Box-Box/box_documents/school/classes/2023/3_fall_2023/CS_340/tweeter_server_2/server/build/libs/server-all.jar --profile personal
arr=(
        "arn:aws:lambda:us-east-1:172849472790:function:tweeter_login"
        "arn:aws:lambda:us-east-1:172849472790:function:tweeter_get_followers"
        "arn:aws:lambda:us-east-1:172849472790:function:tweeter_register"
        "arn:aws:lambda:us-east-1:172849472790:function:tweeter_get_feed"
        "arn:aws:lambda:us-east-1:172849472790:function:tweeter_get_user"
        "arn:aws:lambda:us-east-1:172849472790:function:tweeter_logout"
        "arn:aws:lambda:us-east-1:172849472790:function:tweeter_is_follower"
        "arn:aws:lambda:us-east-1:172849472790:function:tweeter_get_story"
        "arn:aws:lambda:us-east-1:172849472790:function:tweeter_get_followers_count"
        "arn:aws:lambda:us-east-1:172849472790:function:tweeter_follow"
        "arn:aws:lambda:us-east-1:172849472790:function:tweeter_get_following"
        "arn:aws:lambda:us-east-1:172849472790:function:tweeter_post_status"
        "arn:aws:lambda:us-east-1:172849472790:function:tweeter_unfollow"
        "arn:aws:lambda:us-east-1:172849472790:function:tweeter_get_following_count"
    )
for FUNCTION_NAME in "${arr[@]}"
do
  aws lambda update-function-code --function-name $FUNCTION_NAME --zip-file fileb:///Users/taylor_west/Library/CloudStorage/Box-Box/box_documents/school/classes/2023/3_fall_2023/CS_340/tweeter_server_2/server/build/libs/server-all.jar --profile personal &
done